# Generated by Django 5.0.6 on 2024-05-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_property_manager_alter_property_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="core.tenant",
            ),
        ),
    ]
