# Generated by Django 5.0.6 on 2024-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_maintanancerequests_tenant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="tenant",
        ),
        migrations.AddField(
            model_name="property",
            name="tenant",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="properties", to="core.tenant"
            ),
        ),
    ]
