# Generated by Django 5.0.6 on 2024-05-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_property_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="property_manager",
            name="phone_number",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone_number",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="rent",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="property",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="core.tenant",
            ),
        ),
    ]
