# Generated by Django 5.0.6 on 2024-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_property_tenant_property_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="zip_code",
            field=models.CharField(default="00000", max_length=50),
        ),
    ]
