# Generated by Django 5.0.6 on 2024-05-27 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_property_manager_phone_number_tenant_date_of_birth_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Property_Manager",
            new_name="PropertyManager",
        ),
    ]
