# Generated by Django 5.0.6 on 2024-07-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_property_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymanager",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01"),
        ),
    ]
