# Generated by Django 5.0.6 on 2024-06-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_property_manager_propertymanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintananceRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typ", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("status", models.BooleanField(default=False)),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintanance_requests",
                        to="core.property",
                    ),
                ),
            ],
        ),
    ]
