# Generated by Django 5.0.6 on 2024-07-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_propertymanager_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="tenant",
            field=models.ManyToManyField(
                blank=True, related_name="properties", to="core.tenant"
            ),
        ),
    ]
