# Generated by Django 5.0.6 on 2024-06-13 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_maintanancerequests"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
