# Generated by Django 5.0.6 on 2024-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_tenant_created_at_tenant_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertymanager",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
